
title: Rachel Dicken
email: rnb137 AT gmail DOT com
description: > # this means to ignore newlines until "baseurl:"
  # Rachel Dicken's Website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
highlighter: rouge
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

permalink: none

